# This is the model that used for creating new Drag and Drop activity.
# Every game has a name and theme which corresponds to image uploaded by
# the content provider in the first place using CarrierWave Gem.
# Attributes : * name - string.
#              * image - string (Name of the image file on the machine).
#              * id - integer (Auto-increment key generated by the database).
# Constraints : Both image and name should be present.
class DragAndDrop < ActiveRecord::Base
  mount_uploader :image , ImageUploader
  validates :name, :image, presence: true

  # This method is used to Allow accessing model attributes As Rails 4 does
  # not support "attr_accessible" keyword.
  # Parameters : None.
  # Returns : None.
  # Approach : The method is  just making The model's column accessible.
  # Author : Hussien M. Eloy.
  def drag_and_drop_params
    params.require(:drag_and_drop).permit(:name, :image)
  end

end
