# This is the model that used for assigning score to specific
# Drag and Drop activity.
# Each Drag and drop game score has a game associated with it, and integer
# score of the child progress in this activity. 
# Attributes : * score - integer.
#              * drag_and_drop_id - integer.
#              * id - integer (Auto-increment key generated by the database).
# Constraints : drag_and_drop_id is a foreign key of Drag and Drop instance.
class DragAndDropScore < ActiveRecord::Base
  belongs_to :drag_and_drop, foreign_key: 'drag_and_drop_id'  
end
